name: Check Kotlin Code Styling

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '28 1 * * 4'
  workflow_dispatch:

env:
  DETEKT_RELEASE_TAG: v1.15.0

jobs:
  style_check:
    name: Style Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install Detekt
        run: |
          curl -sSLO https://github.com/detekt/detekt/releases/download/${DETEKT_RELEASE_TAG}/detekt
          chmod +x detekt
          sudo mv detekt /usr/local/bin/

      - name: Run Detekt Style Check
        run: |
          detekt --input ${{ github.workspace }} \
                 --report sarif:${{ github.workspace }}/detekt_output/detekt.sarif.json \
                 --excludes '**/build.gradle.kts'

      - name: Check SARIF file existence
        run: |
          ls ${{ github.workspace }}/detekt_output/detekt.sarif.json || echo "SARIF file not found"
