name: Check Kotlin Code Styling

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '28 1 * * 4'
  workflow_dispatch:

env:
  DETEKT_RELEASE_TAG: v1.15.0

jobs:
  style_check:
    name: Style Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run Detekt Style Check
        run: |
          # Run Detekt with specific rules for code styling and output SARIF file
          detekt --input ${{ github.workspace }} --report sarif:${{ github.workspace }}/detekt_output/detekt.sarif.json

      - name: Check SARIF file existence
        run: |
          ls ${{ github.workspace }}/detekt_output/detekt.sarif.json || echo "SARIF file not found"

      - name: Upload Detekt Style Check Results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ github.workspace }}/detekt_output/detekt.sarif.json
          checkout_path: ${{ github.workspace }}
